Source import from linux-sna-0_1_21_tar.bz2

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,7 +3,8 @@
 AUTOMAKE_OPTIONS = 1.3e foreign
 
 BUILD_SUBDIRS = . include libsna libasuite snaconfig snatchd asuite \
-	sense tn3270d tn5250d docs 
+	sense docs 
+# 	tn3270d tn5250d
 SUBDIRS = $(BUILD_SUBDIRS)
 DIST_SUBDIRS = $(BUILD_SUBDIRS) $(CONF_SUBDIRS)
 
@@ -26,7 +27,7 @@ CVS="cvs"
 
 # RPM happenings
 #ifndef RPM_BUILD_DIR
-RPM_BUILD_DIR="/usr/src/redhat"
+RPM_BUILD_DIR="/usr/src/rpm"
 #endif
 #ifndef RPM_BUILD_TARGET
 RPM_BUILD_TARGET=`uname -m`
@@ -67,20 +68,32 @@ pending-patches:
 
 rpm-dist:
 	if ! test -f $(srcdir)/docs/$(PACKAGE).spec; then \
-		echo "RPM spec file '$(PACKAGE).spec' missing from '$(srcdir)/docs' directory; aborting rpm build" 1>&2; \
-		exit 1; \
-	fi; \ 
-	rm -f $(srcdir)/$(PACKAGE)-$(VERSION).tar.gz; \
-	rm -f $(srcdir)/$(PACKAGE)-$(VERSION)-1.src.rpm; \
-	rm -f $(srcdir)/$(PACKAGE)-$(VERSION)-1.$(RPM_BUILD_TARGET).rpm; \
-	cat $(srcdir)/docs/$(PACKAGE).spec | sed s/VERSION/$(VERSION)/g > $(RPM_BUILD_DIR)/SPECS/$(PACKAGE).spec; \
-	$(MAKE) dist; \
-	cp -f $(srcdir)/$(PACKAGE)-$(VERSION).tar.gz $(RPM_BUILD_DIR)/SOURCES/$(PACKAGE)-$(VERSION).tar.gz; \
-	rpm -ba --target=$(RPM_BUILD_TARGET) -v $(RPM_BUILD_DIR)/SPECS/$(PACKAGE).spec; \
-	cp -f $(RPM_BUILD_DIR)/RPMS/$(RPM_BUILD_TARGET)/$(PACKAGE)-$(VERSION)-1.$(RPM_BUILD_TARGET).rpm $(srcdir); \
-	cp -f $(RPM_BUILD_DIR)/SRPMS/$(PACKAGE)-$(VERSION)-1.src.rpm $(srcdir); \
-	rm -f $(RPM_BUILD_DIR)/RPMS/$(RPM_BUILD_TARGET)/$(PACKAGE)-$(VERSION)-1.$(RPM_BUILD_TARGET).rpm; \
-	rm -f $(RPM_BUILD_DIR)/SRPMS/$(PACKAGE)-$(VERSION)-1.src.rpm; \
-	rm -f $(RPM_BUILD_DIR)/SPECS/$(PACKAGE).spec; \
-	rm -f $(RPM_BUILD_DIR)/SOURCES/$(PACKAGE)-$(VERSION).tar.gz; \
-	rm -rf $(RPM_BUILD_DIR)/BUILD/$(PACKAGE)-$(VERSION)
+                echo "RPM spec file '$(PACKAGE).spec' missing from '$(srcdir)/docs' directory; aborting rpm build" 1>&2; \
+                exit 1; \
+        fi; \
+        cat $(srcdir)/docs/$(PACKAGE).spec | sed s/VERSION/$(VERSION)/g > $(RPM_BUILD_DIR)/SPECS/$(PACKAGE).spec; \
+        $(MAKE) dist; \
+        cp -f $(srcdir)/$(PACKAGE)-$(VERSION).tar.gz $(RPM_BUILD_DIR)/SOURCES/$(PACKAGE)-$(VERSION).tar.gz; \
+        rpm -ba -v --sign $(RPM_BUILD_DIR)/SPECS/$(PACKAGE).spec; \
+        rm -f $(RPM_BUILD_DIR)/SPECS/$(PACKAGE).spec; \
+        rm -f $(RPM_BUILD_DIR)/SOURCES/$(PACKAGE)-$(VERSION).tar.gz; \
+        rm -rf $(RPM_BUILD_DIR)/BUILD/$(PACKAGE)-$(VERSION); \
+        $(MAKE) clean-dist; \
+        mkdir -p $(srcdir)/build.tmp; \
+        mkdir -p $(srcdir)/build.tmp/source; \
+        mkdir -p $(srcdir)/build.tmp/binaries; \
+        mkdir -p $(srcdir)/build.tmp/binaries/RPMS; \
+        mkdir -p $(srcdir)/build.tmp/binaries/SRPMS; \
+        mv -f $(PACKAGE)-$(VERSION).tar.gz $(srcdir)/build.tmp/source; \
+        mv -f `find $(RPM_BUILD_DIR)/SRPMS -name "$(PACKAGE)-*.src.rpm" -print` $(srcdir)/build.tmp/binaries/SRPMS/; \
+        mv -f `find $(RPM_BUILD_DIR)/RPMS -name "$(PACKAGE)-*.rpm" -print` $(srcdir)/build.tmp/binaries/RPMS/
+
+ftp-dist:
+	if ! test -d $(srcdir)/build.tmp; then \
+                echo "Build directory '$(srcdir)/build.tmp' missing, run 'make rpm-dist' first" 1>&2; \
+                exit 1; \
+        fi; \
+        ncftpput -R -u jschlst ftp.linux-sna.org /home/ftp/pub/$(PACKAGE)/v0.1/ $(srcdir)/build.tmp/*
+
+clean-dist:
+	rm -rf $(srcdir)/build.tmp
